BEGIN;

-- Full local development schema + sample data for the current project.
-- Run this inside an empty PostgreSQL database, for example gia_pha_db.
-- Seed login accounts:
--   admin@test.com / 123456
--   member@test.com / 123456
--   cuong@test.com / 123456
--   other@test.com / 123456

DROP TABLE IF EXISTS public.album_media CASCADE;
DROP TABLE IF EXISTS public.albums CASCADE;
DROP TABLE IF EXISTS public.edit_requests CASCADE;
DROP TABLE IF EXISTS public.honors CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.posts CASCADE;
DROP TABLE IF EXISTS public.password_reset_tokens CASCADE;
DROP TABLE IF EXISTS public.refresh_tokens CASCADE;
DROP TABLE IF EXISTS public.marriages CASCADE;
DROP TABLE IF EXISTS public.parent_child_relations CASCADE;
DROP TABLE IF EXISTS public.members CASCADE;
DROP TABLE IF EXISTS public.families CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email character varying NOT NULL UNIQUE,
  "passwordHash" character varying NOT NULL,
  name character varying,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.families (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  "originPlace" character varying,
  description text,
  generations integer NOT NULL DEFAULT 1,
  "membersCount" integer NOT NULL DEFAULT 0,
  "coverImageUrl" character varying,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE public.members (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "fullName" character varying NOT NULL,
  "otherName" character varying,
  gender character varying NOT NULL DEFAULT 'unknown',
  generation integer,
  role character varying,
  "dateOfBirth" timestamp without time zone,
  "isDeceased" boolean NOT NULL DEFAULT false,
  "isInLaw" boolean NOT NULL DEFAULT false,
  "dateOfDeath" timestamp without time zone,
  "placeOfBirth" character varying,
  "currentAddress" character varying,
  "avatarUrl" character varying,
  education character varying,
  occupation character varying,
  biography text,
  note text,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT members_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE
);

CREATE TABLE public.parent_child_relations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parentId" integer NOT NULL,
  "childId" integer NOT NULL,
  "relationType" character varying NOT NULL DEFAULT 'parent',
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT parent_child_relations_parentId_fkey
    FOREIGN KEY ("parentId") REFERENCES public.members(id) ON DELETE CASCADE,
  CONSTRAINT parent_child_relations_childId_fkey
    FOREIGN KEY ("childId") REFERENCES public.members(id) ON DELETE CASCADE
);

CREATE TABLE public.marriages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "memberAId" integer NOT NULL,
  "memberBId" integer NOT NULL,
  status character varying NOT NULL DEFAULT 'ACTIVE',
  "marriedAt" timestamp without time zone,
  "endedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT marriages_memberAId_fkey
    FOREIGN KEY ("memberAId") REFERENCES public.members(id) ON DELETE CASCADE,
  CONSTRAINT marriages_memberBId_fkey
    FOREIGN KEY ("memberBId") REFERENCES public.members(id) ON DELETE CASCADE
);

CREATE TABLE public.refresh_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "tokenHash" character varying NOT NULL UNIQUE,
  "expiresAt" timestamp without time zone NOT NULL,
  "revokedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT refresh_tokens_userId_fkey
    FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.password_reset_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "tokenHash" character varying NOT NULL UNIQUE,
  "expiresAt" timestamp without time zone NOT NULL,
  "usedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT password_reset_tokens_userId_fkey
    FOREIGN KEY ("userId") REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE TABLE public.posts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "authorId" integer NOT NULL,
  title character varying NOT NULL,
  slug character varying,
  summary text,
  content text NOT NULL,
  category character varying,
  status character varying NOT NULL DEFAULT 'DRAFT',
  visibility character varying NOT NULL DEFAULT 'FAMILY',
  "thumbnailUrl" character varying,
  "publishedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "deletedAt" timestamp without time zone,
  CONSTRAINT posts_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE,
  CONSTRAINT posts_authorId_fkey
    FOREIGN KEY ("authorId") REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "createdById" integer NOT NULL,
  "relatedMemberId" integer,
  title character varying NOT NULL,
  description text,
  "eventType" character varying NOT NULL DEFAULT 'OTHER',
  status character varying NOT NULL DEFAULT 'UPCOMING',
  visibility character varying NOT NULL DEFAULT 'FAMILY',
  "startAt" timestamp without time zone NOT NULL,
  "endAt" timestamp without time zone,
  location character varying,
  "coverImageUrl" character varying,
  "isRecurring" boolean NOT NULL DEFAULT false,
  "recurrenceRule" character varying,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "deletedAt" timestamp without time zone,
  CONSTRAINT events_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE,
  CONSTRAINT events_createdById_fkey
    FOREIGN KEY ("createdById") REFERENCES public.users(id) ON DELETE RESTRICT,
  CONSTRAINT events_relatedMemberId_fkey
    FOREIGN KEY ("relatedMemberId") REFERENCES public.members(id) ON DELETE SET NULL
);

CREATE TABLE public.honors (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "memberId" integer NOT NULL,
  "createdById" integer NOT NULL,
  title character varying NOT NULL,
  "honorType" character varying NOT NULL DEFAULT 'OTHER',
  description text,
  achievement text,
  "imageUrl" character varying,
  "documentUrl" character varying,
  "awardedAt" timestamp without time zone,
  "startAt" timestamp without time zone,
  "endAt" timestamp without time zone,
  status character varying NOT NULL DEFAULT 'ACTIVE',
  "displayOrder" integer NOT NULL DEFAULT 0,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "deletedAt" timestamp without time zone,
  CONSTRAINT honors_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE,
  CONSTRAINT honors_memberId_fkey
    FOREIGN KEY ("memberId") REFERENCES public.members(id) ON DELETE CASCADE,
  CONSTRAINT honors_createdById_fkey
    FOREIGN KEY ("createdById") REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.edit_requests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "targetMemberId" integer NOT NULL,
  "requestType" character varying NOT NULL DEFAULT 'edit_member',
  status character varying NOT NULL DEFAULT 'PENDING',
  changes jsonb NOT NULL,
  reason text NOT NULL,
  "submittedByName" character varying NOT NULL,
  "submittedByPhone" character varying,
  "reviewedBy" character varying,
  "adminNote" text,
  "reviewedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT edit_requests_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE,
  CONSTRAINT edit_requests_targetMemberId_fkey
    FOREIGN KEY ("targetMemberId") REFERENCES public.members(id) ON DELETE CASCADE
);

CREATE TABLE public.albums (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "familyId" integer NOT NULL,
  "createdById" integer NOT NULL,
  title character varying NOT NULL,
  description text,
  "coverImage" text,
  visibility character varying NOT NULL DEFAULT 'INTERNAL',
  status character varying NOT NULL DEFAULT 'VISIBLE',
  "notifiedAt" timestamp without time zone,
  "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
  "deletedAt" timestamp without time zone,
  CONSTRAINT albums_familyId_fkey
    FOREIGN KEY ("familyId") REFERENCES public.families(id) ON DELETE CASCADE,
  CONSTRAINT albums_createdById_fkey
    FOREIGN KEY ("createdById") REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE public.album_media (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "albumId" integer NOT NULL,
  type character varying NOT NULL,
  url text NOT NULL,
  "thumbnailUrl" text,
  "fileName" character varying NOT NULL,
  description text,
  "uploadedById" integer NOT NULL,
  "uploadedAt" timestamp without time zone NOT NULL,
  "deletedAt" timestamp without time zone,
  CONSTRAINT album_media_albumId_fkey
    FOREIGN KEY ("albumId") REFERENCES public.albums(id) ON DELETE CASCADE,
  CONSTRAINT album_media_uploadedById_fkey
    FOREIGN KEY ("uploadedById") REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE INDEX users_email_idx ON public.users (email);
CREATE INDEX members_family_id_idx ON public.members ("familyId");
CREATE INDEX parent_child_parent_id_idx ON public.parent_child_relations ("parentId");
CREATE INDEX parent_child_child_id_idx ON public.parent_child_relations ("childId");
CREATE INDEX marriages_member_a_id_idx ON public.marriages ("memberAId");
CREATE INDEX marriages_member_b_id_idx ON public.marriages ("memberBId");
CREATE INDEX posts_family_id_idx ON public.posts ("familyId");
CREATE INDEX posts_author_id_idx ON public.posts ("authorId");
CREATE INDEX events_family_id_idx ON public.events ("familyId");
CREATE INDEX events_created_by_id_idx ON public.events ("createdById");
CREATE INDEX honors_family_id_idx ON public.honors ("familyId");
CREATE INDEX edit_requests_family_id_idx ON public.edit_requests ("familyId");
CREATE INDEX albums_family_id_idx ON public.albums ("familyId");
CREATE INDEX album_media_album_id_idx ON public.album_media ("albumId");

INSERT INTO public.users (id, email, "passwordHash", name, "createdAt", "updatedAt") VALUES
  (1, 'admin@test.com', 'b156181b1f10a3d5fde7de41716c8e7d:95effbbff8c73fe5d7e1e0572ef581d1e56b387d62b6bb450d854e778372a34c84741737c87c7cd1b9635e6a09a3abb19e38a10af45b69a7f77fd9f36bac0670', 'Nguyễn Văn Trưởng', '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (2, 'member@test.com', 'fddffaa52b6abc5644b8b433c62ab0fb:4479325f6d30376166b080b9334562f15b3ebef1d63403703e9ce17da36fddbb54d5a522417075ef52463bd2f73506a65dc6433e87fc6e8bf5a340c098b03b02', 'Nguyễn Thị B', '2026-07-01 08:05:00', '2026-07-01 08:05:00'),
  (3, 'cuong@test.com', 'fd7c1eb07208d5a641406ddf600daa81:6556ec784a91fb032a40ddfecf591b691b994c6499de9d08259c092cfa0271de172ce689b490f49d9938f2f2cb0e061c053b74403943007cbd91b0c2f207cc41', 'Nguyễn Minh Cường', '2026-07-01 08:10:00', '2026-07-01 08:10:00'),
  (4, 'other@test.com', '1d61b03bc0de5385b59d8a1fdaaafd8c:fdf9f8fed92542d9279b31e0b4ccfb3339b0d3f5c4d13d46bc369255a4771ae9574ffab00061f54704afdef66dc2fe3be87f406085414bf8d8efb394c4749611', 'Trần Văn Quản', '2026-07-01 08:15:00', '2026-07-01 08:15:00');

INSERT INTO public.families (id, name, "originPlace", description, generations, "membersCount", "coverImageUrl", "createdAt", "updatedAt") VALUES
  (1, 'Gia phả họ Nguyễn', 'Thôn Đông, Hà Nội', 'Dữ liệu mẫu cho họ Nguyễn, dùng để kiểm thử cây gia phả, bài viết, sự kiện và thư viện.', 3, 11, 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?auto=format&fit=crop&w=1200&q=80', '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (2, 'Gia phả họ Trần', 'Nam Định', 'Gia đình mẫu thứ hai để kiểm thử phân quyền và dữ liệu công khai/nội bộ.', 2, 2, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00');

INSERT INTO public.members (id, "familyId", "fullName", "otherName", gender, generation, role, "dateOfBirth", "isDeceased", "isInLaw", "dateOfDeath", "placeOfBirth", "currentAddress", "avatarUrl", education, occupation, biography, note, "createdAt", "updatedAt") VALUES
  (1, 1, 'Nguyễn Văn A', NULL, 'male', 1, 'Trưởng tộc', '1940-01-01', true, false, '2015-01-01', 'Hà Nội', 'Hà Nội', NULL, NULL, 'Nông nghiệp', 'Bậc cao niên đời thứ nhất trong dữ liệu mẫu.', NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (2, 1, 'Lê Thị B', NULL, 'female', 1, NULL, '1945-01-01', false, true, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (3, 1, 'Nguyễn Văn C', NULL, 'male', 2, 'Trưởng chi', '1968-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, 'Đại học', 'Cán bộ hưu trí', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (4, 1, 'Trần Thị D', NULL, 'female', 2, NULL, '1970-01-01', false, true, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (5, 1, 'Nguyễn Thị E', NULL, 'female', 2, NULL, '1972-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (7, 1, 'Nguyễn Văn G', NULL, 'male', 3, NULL, '1995-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, 'Đại học', 'Kỹ sư', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (8, 1, 'Nguyễn Thị H', NULL, 'female', 3, NULL, '1998-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, 'Đại học', 'Giáo viên', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (9, 1, 'Hoàng Văn K', NULL, 'male', 3, NULL, '2000-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (10, 1, 'Lê Văn Phụ', NULL, 'male', 2, NULL, '1969-01-01', false, true, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (11, 1, 'Phạm Thị M', 'Vợ 2', 'female', 2, NULL, '1975-01-01', false, true, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (12, 1, 'Nguyễn Văn N', NULL, 'male', 3, NULL, '2005-01-01', false, false, NULL, 'Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (20, 2, 'Trần Văn Nghĩa', NULL, 'male', 1, 'Trưởng họ', '1965-01-01', false, false, NULL, 'Nam Định', 'Nam Định', NULL, NULL, 'Thợ mộc', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (21, 2, 'Trần Thị Hoa', NULL, 'female', 2, NULL, '1994-01-01', false, false, NULL, 'Nam Định', 'Nam Định', NULL, NULL, NULL, NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00');

INSERT INTO public.marriages (id, "memberAId", "memberBId", status, "marriedAt", "endedAt", "createdAt", "updatedAt") VALUES
  (1, 1, 2, 'ACTIVE', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (2, 3, 4, 'ACTIVE', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (3, 5, 10, 'ACTIVE', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00'),
  (4, 3, 11, 'ACTIVE', NULL, NULL, '2026-07-01 08:00:00', '2026-07-01 08:00:00');

INSERT INTO public.parent_child_relations (id, "parentId", "childId", "relationType", "createdAt") VALUES
  (1, 1, 3, 'biological_child', '2026-07-01 08:00:00'),
  (2, 1, 5, 'biological_child', '2026-07-01 08:00:00'),
  (3, 3, 7, 'biological_child', '2026-07-01 08:00:00'),
  (4, 4, 7, 'biological_child', '2026-07-01 08:00:00'),
  (5, 3, 8, 'biological_child', '2026-07-01 08:00:00'),
  (6, 4, 8, 'biological_child', '2026-07-01 08:00:00'),
  (7, 5, 9, 'biological_child', '2026-07-01 08:00:00'),
  (8, 3, 12, 'biological_child', '2026-07-01 08:00:00'),
  (9, 11, 12, 'biological_child', '2026-07-01 08:00:00');

INSERT INTO public.events (id, "familyId", "createdById", "relatedMemberId", title, description, "eventType", status, visibility, "startAt", "endAt", location, "coverImageUrl", "isRecurring", "recurrenceRule", "createdAt", "updatedAt", "deletedAt") VALUES
  (1, 1, 1, NULL, 'Ngày giỗ cụ Tổ Nguyễn Văn Khai', 'Con cháu tập trung dâng hương, đọc gia phả và dùng bữa cơm họ.', 'DEATH_ANNIVERSARY', 'UPCOMING', 'PUBLIC', '2026-07-22 08:00:00', '2026-07-22 11:30:00', 'Từ đường họ Nguyễn, thôn Đông', NULL, true, $json${"inputCalendar":"LUNAR","recurrence":{"frequency":"YEARLY","interval":1},"seriesId":"series-death-anniversary-khai","occurrenceId":"occ-2026-death-anniversary-khai","recurrenceDate":"2026-07-22","reminders":[{"id":"rem-001-1","minutesBefore":1440,"label":"Trước 1 ngày"},{"id":"rem-001-2","minutesBefore":60,"label":"Trước 1 giờ"}],"sendNotification":true}$json$, '2026-07-01 09:00:00', '2026-07-10 10:20:00', NULL),
  (2, 1, 1, NULL, 'Họp họ quý III', 'Bàn kế hoạch tu sửa nhà thờ họ và phân công chuẩn bị lễ cuối năm.', 'FAMILY_MEETING', 'UPCOMING', 'FAMILY', '2026-07-27 19:00:00', '2026-07-27 21:00:00', 'Nhà văn hóa thôn', NULL, true, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"MONTHLY","interval":3,"count":4},"seriesId":"series-family-meeting-quarterly","occurrenceId":"occ-2026-q3-family-meeting","recurrenceDate":"2026-07-27","reminders":[{"id":"rem-002-1","minutesBefore":120,"label":"Trước 2 giờ"}],"sendNotification":true}$json$, '2026-07-05 08:10:00', '2026-07-05 08:10:00', NULL),
  (3, 1, 1, NULL, 'Lễ cưới Nguyễn Minh Quân', 'Gia đình kính mời bà con tham dự lễ thành hôn của Minh Quân và Thu Hà.', 'WEDDING', 'UPCOMING', 'PUBLIC', '2026-08-02 10:30:00', '2026-08-02 13:30:00', 'Trung tâm tiệc cưới Hoa Sen', NULL, false, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"NONE","interval":1},"reminders":[{"id":"rem-003-1","minutesBefore":1440,"label":"Trước 1 ngày"}],"sendNotification":false}$json$, '2026-07-12 11:00:00', '2026-07-12 11:00:00', NULL),
  (4, 1, 1, NULL, 'Mừng thọ cụ bà Nguyễn Thị Lan', 'Con cháu chúc thọ và chụp ảnh lưu niệm cùng cụ.', 'LONGEVITY_CELEBRATION', 'UPCOMING', 'FAMILY', '2026-08-09 09:00:00', '2026-08-09 11:00:00', 'Nhà riêng cụ Lan', NULL, true, $json${"inputCalendar":"LUNAR","recurrence":{"frequency":"YEARLY","interval":1},"seriesId":"series-longevity-lan","occurrenceId":"occ-2026-longevity-lan","recurrenceDate":"2026-08-09","reminders":[{"id":"rem-004-1","minutesBefore":10080,"label":"Trước 1 tuần"},{"id":"rem-004-2","minutesBefore":1440,"label":"Trước 1 ngày"}],"sendNotification":true}$json$, '2026-07-09 07:45:00', '2026-07-09 07:45:00', NULL),
  (5, 1, 1, NULL, 'Trao học bổng khuyến học', 'Trao phần thưởng cho con cháu đạt thành tích cao trong năm học.', 'SCHOLARSHIP', 'UPCOMING', 'PUBLIC', '2026-08-16 15:00:00', '2026-08-16 17:00:00', 'Sân từ đường', NULL, true, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"YEARLY","interval":1},"seriesId":"series-scholarship","occurrenceId":"occ-2026-scholarship","recurrenceDate":"2026-08-16","reminders":[{"id":"rem-005-1","minutesBefore":2880,"label":"Trước 2 ngày"}],"sendNotification":true}$json$, '2026-07-14 12:00:00', '2026-07-14 12:00:00', NULL),
  (6, 1, 1, NULL, 'Kỷ niệm ngày xây dựng từ đường', 'Ôn lại lịch sử xây dựng từ đường và tri ân các bậc tiền nhân.', 'ANNIVERSARY', 'COMPLETED', 'PUBLIC', '2026-07-12 08:30:00', '2026-07-12 10:00:00', 'Từ đường họ Nguyễn', NULL, true, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"YEARLY","interval":1},"seriesId":"series-ancestral-house-anniversary","occurrenceId":"occ-2026-ancestral-house-anniversary","recurrenceDate":"2026-07-12","reminders":[{"id":"rem-006-1","minutesBefore":1440,"label":"Trước 1 ngày"}],"sendNotification":true}$json$, '2026-06-25 10:00:00', '2026-07-12 11:00:00', NULL),
  (7, 1, 1, NULL, 'Gặp mặt chi họ miền Nam', 'Buổi gặp mặt định kỳ của chi họ đang sinh sống tại miền Nam.', 'FAMILY_MEETING', 'CANCELLED', 'FAMILY', '2026-07-25 18:00:00', '2026-07-25 20:30:00', 'TP. Hồ Chí Minh', NULL, true, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"MONTHLY","interval":1},"seriesId":"series-southern-branch-meeting","occurrenceId":"occ-2026-07-southern-branch-meeting","recurrenceDate":"2026-07-25","reminders":[{"id":"rem-007-1","minutesBefore":180,"label":"Trước 3 giờ"}],"sendNotification":true,"cancelReason":"Trưởng chi họ bận việc đột xuất, sẽ dời sang tháng sau."}$json$, '2026-07-03 17:20:00', '2026-07-20 09:15:00', NULL),
  (8, 1, 1, NULL, 'Dọn dẹp và kiểm kê đồ thờ', 'Kiểm kê vật dụng, vệ sinh khuôn viên và chuẩn bị hạng mục cần sửa.', 'OTHER', 'ONGOING', 'FAMILY', '2026-07-21 07:30:00', '2026-07-23 17:00:00', 'Từ đường họ Nguyễn', NULL, false, $json${"inputCalendar":"SOLAR","recurrence":{"frequency":"NONE","interval":1},"reminders":[{"id":"rem-008-1","minutesBefore":60,"label":"Trước 1 giờ"}],"sendNotification":false}$json$, '2026-07-11 13:30:00', '2026-07-21 07:30:00', NULL);

INSERT INTO public.posts (id, "familyId", "authorId", title, slug, summary, content, category, status, visibility, "thumbnailUrl", "publishedAt", "createdAt", "updatedAt", "deletedAt") VALUES
  (1, 1, 1, 'Lễ dâng hương đầu xuân tại từ đường họ Nguyễn', 'le-dang-huong-dau-xuan-tai-tu-duong-ho-nguyen', 'Con cháu các chi họ cùng về từ đường dâng hương, ôn lại gia phong và bàn việc khuyến học trong năm mới.', 'Sáng mùng 8 tháng Giêng, con cháu họ Nguyễn từ nhiều nơi đã có mặt tại từ đường chính để dự lễ dâng hương đầu xuân. Buổi lễ diễn ra trang nghiêm với phần đọc chúc văn, tưởng nhớ công đức tổ tiên và báo cáo những việc dòng họ đã làm được trong năm qua.', 'Hoạt động dòng họ', 'PUBLISHED', 'PUBLIC', 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?auto=format&fit=crop&w=1200&q=80', '2026-02-24 09:00:00', '2026-02-20 20:15:00', '2026-02-24 09:00:00', NULL),
  (2, 1, 2, 'Danh sách học sinh nhận thưởng khuyến học năm 2026', 'danh-sach-hoc-sinh-nhan-thuong-khuyen-hoc-nam-2026', 'Quỹ khuyến học dòng họ công bố danh sách con cháu đạt thành tích nổi bật trong năm học vừa qua.', 'Ban khuyến học họ Nguyễn đã tổng hợp thành tích học tập của con cháu trong năm học 2025 - 2026. Lễ trao thưởng dự kiến tổ chức trong ngày họp mặt cuối tháng Bảy.', 'Khuyến học', 'PUBLISHED', 'FAMILY', 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80', '2026-07-05 07:30:00', '2026-07-02 14:10:00', '2026-07-05 07:30:00', NULL),
  (3, 1, 1, 'Ghi chép về cụ Nguyễn Văn Thành trong gia phả cũ', 'ghi-chep-ve-cu-nguyen-van-thanh-trong-gia-pha-cu', 'Một số tư liệu mới tìm được giúp bổ sung mốc thời gian và nơi sinh sống của cụ Nguyễn Văn Thành.', 'Trong quá trình rà soát bản gia phả chép tay lưu tại nhà thờ chi 2, ban biên tập tìm thấy thêm ghi chú liên quan đến cụ Nguyễn Văn Thành.', 'Lịch sử và truyền thống', 'DRAFT', 'FAMILY', NULL, NULL, '2026-06-15 21:45:00', '2026-07-01 19:20:00', NULL),
  (4, 1, 1, 'Thông báo tạm hoãn buổi họp đại diện các chi', 'thong-bao-tam-hoan-buoi-hop-dai-dien-cac-chi', 'Do điều kiện thời tiết, buổi họp đại diện các chi dự kiến cuối tuần này sẽ được chuyển sang tuần sau.', 'Ban liên lạc dòng họ thông báo tạm hoãn buổi họp đại diện các chi dự kiến tổ chức vào Chủ nhật tuần này.', 'Thông báo', 'ARCHIVED', 'PUBLIC', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80', '2026-07-18 08:00:00', '2026-07-17 22:00:00', '2026-07-20 06:30:00', NULL),
  (5, 1, 3, 'Gương sáng dòng họ: bác sĩ Nguyễn Minh Cường', 'guong-sang-dong-ho-bac-si-nguyen-minh-cuong', 'Câu chuyện về bác sĩ trẻ trở về quê tổ chức khám sức khỏe miễn phí cho các cụ cao niên trong họ.', 'Bác sĩ Nguyễn Minh Cường, con cháu chi 4, hiện công tác tại một bệnh viện tuyến trung ương. Trong dịp về quê vừa qua, anh đã phối hợp với trạm y tế xã tổ chức buổi kiểm tra sức khỏe.', 'Văn hóa dòng họ', 'PUBLISHED', 'PUBLIC', 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80', '2026-06-12 10:30:00', '2026-06-10 18:00:00', '2026-06-12 10:30:00', NULL),
  (6, 2, 4, 'Tin nội bộ họ Trần về việc bổ sung phả hệ', 'tin-noi-bo-ho-tran-ve-viec-bo-sung-pha-he', 'Bài nội bộ thuộc dòng họ khác, dùng để kiểm tra giới hạn xem và quản lý theo familyId.', 'Nội dung này phục vụ kiểm thử phân quyền giữa các dòng họ khác nhau.', 'Khác', 'PUBLISHED', 'FAMILY', NULL, '2026-05-02 08:20:00', '2026-04-30 09:00:00', '2026-05-02 08:20:00', NULL),
  (7, 1, 1, 'Kế hoạch sưu tầm ảnh tư liệu các đời', 'ke-hoach-suu-tam-anh-tu-lieu-cac-doi', 'Ban gia phả kêu gọi con cháu gửi ảnh cũ, giấy tờ và kỷ vật để số hóa, lưu giữ lâu dài.', 'Trong tháng tới, ban gia phả sẽ mở đợt sưu tầm ảnh tư liệu các đời. Những ảnh chân dung, ảnh lễ họ, giấy chứng nhận, bản chép tay hoặc kỷ vật đều có giá trị lưu giữ.', 'Tin dòng họ', 'PUBLISHED', 'FAMILY', NULL, '2026-07-14 16:00:00', '2026-07-11 09:30:00', '2026-07-14 16:00:00', NULL),
  (8, 2, 4, 'Gương sáng họ Trần: người gìn giữ nghề mộc truyền thống', 'guong-sang-ho-tran-nguoi-gin-giu-nghe-moc-truyen-thong', 'Bài công khai thuộc dòng họ khác, dùng để kiểm tra người quản lý họ Nguyễn có thể xem nhưng không thể thao tác.', 'Ông Trần Văn Nghĩa nhiều năm gìn giữ nghề mộc truyền thống của gia đình và truyền lại cho con cháu trong làng.', 'Gương sáng', 'PUBLISHED', 'PUBLIC', NULL, '2026-04-12 08:00:00', '2026-04-10 20:30:00', '2026-04-12 08:00:00', NULL);

ALTER TABLE public.posts
  ALTER COLUMN content TYPE jsonb
  USING CASE
    WHEN content IS NULL OR btrim(content::text) = '' THEN '[]'::jsonb
    ELSE jsonb_build_array(
      jsonb_build_object(
        'id', concat('seed-post-', id, '-content-1'),
        'type', 'PARAGRAPH',
        'text', content::text
      )
    )
  END;

INSERT INTO public.honors (id, "familyId", "memberId", "createdById", title, "honorType", description, achievement, "imageUrl", "documentUrl", "awardedAt", "startAt", "endAt", status, "displayOrder", "createdAt", "updatedAt", "deletedAt") VALUES
  (1, 1, 7, 1, 'Gương sáng học tập', 'SCHOLARSHIP', 'Vinh danh thành tích học tập nổi bật.', 'Đạt giải học sinh giỏi cấp huyện.', NULL, NULL, '2026-06-20 09:00:00', NULL, NULL, 'ACTIVE', 1, '2026-06-20 09:00:00', '2026-06-20 09:00:00', NULL),
  (2, 1, 3, 1, 'Đóng góp xây dựng từ đường', 'CONTRIBUTION', 'Ghi nhận đóng góp trong quá trình tu sửa từ đường.', 'Tham gia điều phối và đóng góp kinh phí.', NULL, NULL, '2026-05-18 09:00:00', NULL, NULL, 'ACTIVE', 2, '2026-05-18 09:00:00', '2026-05-18 09:00:00', NULL);

INSERT INTO public.edit_requests (id, "familyId", "targetMemberId", "requestType", status, changes, reason, "submittedByName", "submittedByPhone", "reviewedBy", "adminNote", "reviewedAt", "createdAt", "updatedAt") VALUES
  (1, 1, 8, 'edit_member', 'PENDING', '{"occupation":{"old":"Giáo viên","new":"Giáo viên trung học"}}'::jsonb, 'Cập nhật nghề nghiệp mới cho thành viên.', 'Nguyễn Thị H', '0900000001', NULL, NULL, NULL, '2026-07-18 08:00:00', '2026-07-18 08:00:00');

INSERT INTO public.albums (id, "familyId", "createdById", title, description, "coverImage", visibility, status, "notifiedAt", "createdAt", "updatedAt", "deletedAt") VALUES
  (1, 1, 1, 'Lễ Thanh Minh 2026', 'Những khoảnh khắc con cháu về tảo mộ, dâng hương và gặp mặt đầu năm.', 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?auto=format&fit=crop&w=1200&q=80', 'PUBLIC', 'VISIBLE', '2026-04-05 08:05:00', '2026-04-05 08:00:00', '2026-04-05 11:30:00', NULL),
  (2, 1, 1, 'Khánh thành từ đường', 'Album nội bộ ghi lại quá trình hoàn thiện và lễ khánh thành từ đường họ Nguyễn.', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80', 'INTERNAL', 'VISIBLE', '2026-05-18 07:35:00', '2026-05-18 07:30:00', '2026-05-18 12:10:00', NULL),
  (3, 1, 1, 'Trao thưởng khuyến học', 'Hình ảnh các cháu nhận phần thưởng khuyến học của dòng họ.', 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80', 'PUBLIC', 'VISIBLE', '2026-06-20 15:05:00', '2026-06-20 15:00:00', '2026-06-20 17:20:00', NULL),
  (4, 1, 1, 'Tư liệu ảnh cũ', 'Album đang rà soát lại thông tin trước khi hiển thị cho mọi người.', 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80', 'INTERNAL', 'HIDDEN', NULL, '2026-03-10 09:00:00', '2026-07-01 09:00:00', NULL);

INSERT INTO public.album_media (id, "albumId", type, url, "thumbnailUrl", "fileName", description, "uploadedById", "uploadedAt", "deletedAt") VALUES
  (1, 1, 'IMAGE', 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?auto=format&fit=crop&w=600&q=80', 'dang-huong-mo-to.webp', 'Con cháu chuẩn bị lễ vật và dâng hương tại phần mộ tổ.', 1, '2026-04-05 08:20:00', NULL),
  (2, 1, 'IMAGE', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=80', 'gap-mat-sau-le.webp', 'Các gia đình chụp ảnh lưu niệm sau phần lễ chính.', 1, '2026-04-05 10:15:00', NULL),
  (3, 1, 'VIDEO', 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm', 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=600&q=80', 'doc-gia-pha.webm', 'Video ghi lại phần đọc tên các chi trong gia phả.', 1, '2026-04-05 10:40:00', NULL),
  (4, 2, 'IMAGE', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=600&q=80', 'cong-tu-duong-moi.webp', 'Cổng từ đường sau khi hoàn thiện.', 1, '2026-05-18 08:00:00', NULL),
  (5, 2, 'VIDEO', 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80', 'nghi-thuc-khanh-thanh.mp4', 'Đoạn video ngắn ghi lại nghi thức khánh thành.', 1, '2026-05-18 09:30:00', NULL),
  (6, 3, 'IMAGE', 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=600&q=80', 'trao-giay-khen.webp', 'Các cháu đạt thành tích cao nhận giấy khen từ ban khuyến học.', 1, '2026-06-20 15:45:00', NULL),
  (7, 4, 'IMAGE', 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1200&q=80', 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=600&q=80', 'hop-ho-1998.webp', 'Ảnh scan từ buổi họp họ năm 1998, đang xác minh thông tin.', 1, '2026-03-10 09:20:00', NULL);

SELECT setval(pg_get_serial_sequence('public.users', 'id'), COALESCE((SELECT MAX(id) FROM public.users), 1), true);
SELECT setval(pg_get_serial_sequence('public.families', 'id'), COALESCE((SELECT MAX(id) FROM public.families), 1), true);
SELECT setval(pg_get_serial_sequence('public.members', 'id'), COALESCE((SELECT MAX(id) FROM public.members), 1), true);
SELECT setval(pg_get_serial_sequence('public.parent_child_relations', 'id'), COALESCE((SELECT MAX(id) FROM public.parent_child_relations), 1), true);
SELECT setval(pg_get_serial_sequence('public.marriages', 'id'), COALESCE((SELECT MAX(id) FROM public.marriages), 1), true);
SELECT setval(pg_get_serial_sequence('public.refresh_tokens', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.password_reset_tokens', 'id'), 1, false);
SELECT setval(pg_get_serial_sequence('public.posts', 'id'), COALESCE((SELECT MAX(id) FROM public.posts), 1), true);
SELECT setval(pg_get_serial_sequence('public.events', 'id'), COALESCE((SELECT MAX(id) FROM public.events), 1), true);
SELECT setval(pg_get_serial_sequence('public.honors', 'id'), COALESCE((SELECT MAX(id) FROM public.honors), 1), true);
SELECT setval(pg_get_serial_sequence('public.edit_requests', 'id'), COALESCE((SELECT MAX(id) FROM public.edit_requests), 1), true);
SELECT setval(pg_get_serial_sequence('public.albums', 'id'), COALESCE((SELECT MAX(id) FROM public.albums), 1), true);
SELECT setval(pg_get_serial_sequence('public.album_media', 'id'), COALESCE((SELECT MAX(id) FROM public.album_media), 1), true);

COMMIT;
